<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AddDemoCoursesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $demoCourses = [
            // Category 6: Phát triển di động
            [
                'instructor_id' => null,
                'category_id' => 6,
                'title' => 'React Native cơ bản đến ứng dụng thực tế',
                'slug' => 'react-native-co-ban',
                'short_description' => 'Xây dựng ứng dụng di động đa nền tảng với React Native từ A-Z.',
                'description' => '<p>Học cách phát triển ứng dụng mobile cho iOS và Android chỉ với một mã nguồn. Khóa học bao gồm: Component, Navigation, API integration, Authentication, và publish app lên stores.</p>',
                'price' => 649000.00,
                'compare_at_price' => 1290000.00,
                'thumbnail_path' => 'react-native.jpg',
                'status' => 'published',
                'total_duration' => 25,
                'level' => 'intermediate',
                'language' => 'Vietnamese',
                'enrolled_students' => 1850,
                'rating' => 4.6,
                'rating_count' => 420,
                'video_count' => 145,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => null,
                'category_id' => 6,
                'title' => 'Flutter & Dart - Xây dựng App đa nền tảng',
                'slug' => 'flutter-dart-app',
                'short_description' => 'Tạo ứng dụng mobile đẹp mắt với Flutter framework từ Google.',
                'description' => '<p>Làm chủ Flutter và Dart để xây dựng ứng dụng native performance. Học Material Design, State Management (Provider, Bloc), Firebase integration, và best practices.</p>',
                'price' => 699000.00,
                'compare_at_price' => 1390000.00,
                'thumbnail_path' => 'flutter-dart.jpg',
                'status' => 'published',
                'total_duration' => 28,
                'level' => 'intermediate',
                'language' => 'Vietnamese',
                'enrolled_students' => 2100,
                'rating' => 4.7,
                'rating_count' => 580,
                'video_count' => 168,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => null,
                'category_id' => 6,
                'title' => 'iOS Development với Swift & SwiftUI',
                'slug' => 'ios-swift-swiftui',
                'short_description' => 'Phát triển ứng dụng iOS hiện đại với Swift và SwiftUI.',
                'description' => '<p>Xây dựng ứng dụng iPhone/iPad từ đầu. Học Swift programming, SwiftUI declarative syntax, CoreData, networking, và publish lên App Store.</p>',
                'price' => 749000.00,
                'compare_at_price' => 1490000.00,
                'thumbnail_path' => 'ios-swift.jpg',
                'status' => 'published',
                'total_duration' => 32,
                'level' => 'intermediate',
                'language' => 'Vietnamese',
                'enrolled_students' => 1420,
                'rating' => 4.5,
                'rating_count' => 310,
                'video_count' => 152,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => null,
                'category_id' => 6,
                'title' => 'Android Development với Kotlin',
                'slug' => 'android-kotlin',
                'short_description' => 'Tạo ứng dụng Android với Kotlin và Jetpack Compose.',
                'description' => '<p>Học lập trình Android hiện đại với Kotlin. Khóa học bao gồm: Activity/Fragment, MVVM, Room Database, Retrofit, Jetpack Compose, và testing.</p>',
                'price' => 699000.00,
                'compare_at_price' => 1390000.00,
                'thumbnail_path' => 'android-kotlin.jpg',
                'status' => 'published',
                'total_duration' => 30,
                'level' => 'intermediate',
                'language' => 'Vietnamese',
                'enrolled_students' => 1680,
                'rating' => 4.6,
                'rating_count' => 380,
                'video_count' => 158,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Category 7: Marketing số
            [
                'instructor_id' => null,
                'category_id' => 7,
                'title' => 'SEO từ cơ bản đến chuyên sâu',
                'slug' => 'seo-co-ban-chuyen-sau',
                'short_description' => 'Tối ưu website lên TOP Google với kỹ thuật SEO hiện đại.',
                'description' => '<p>Làm chủ SEO onpage/offpage, keyword research, technical SEO, link building, Google Analytics/Search Console. Học cách tăng traffic tự nhiên và ranking bền vững.</p>',
                'price' => 549000.00,
                'compare_at_price' => 1090000.00,
                'thumbnail_path' => 'seo-marketing.jpg',
                'status' => 'published',
                'total_duration' => 22,
                'level' => 'beginner',
                'language' => 'Vietnamese',
                'enrolled_students' => 3200,
                'rating' => 4.7,
                'rating_count' => 890,
                'video_count' => 128,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => null,
                'category_id' => 7,
                'title' => 'Facebook Ads & Google Ads thực chiến',
                'slug' => 'facebook-google-ads',
                'short_description' => 'Chạy quảng cáo hiệu quả trên Facebook và Google.',
                'description' => '<p>Tạo và tối ưu chiến dịch quảng cáo trên Facebook Ads Manager và Google Ads. Học targeting, bidding, conversion tracking, A/B testing, và tối ưu ROI.</p>',
                'price' => 599000.00,
                'compare_at_price' => 1190000.00,
                'thumbnail_path' => 'fb-gg-ads.jpg',
                'status' => 'published',
                'total_duration' => 26,
                'level' => 'intermediate',
                'language' => 'Vietnamese',
                'enrolled_students' => 2850,
                'rating' => 4.6,
                'rating_count' => 720,
                'video_count' => 142,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => null,
                'category_id' => 7,
                'title' => 'Content Marketing & Copywriting',
                'slug' => 'content-marketing-copywriting',
                'short_description' => 'Viết content thu hút và chuyển đổi khách hàng hiệu quả.',
                'description' => '<p>Học cách viết content marketing, blog SEO, email marketing, landing page copy. Nắm vững storytelling, AIDA, hook, CTA và chiến lược nội dung toàn diện.</p>',
                'price' => 499000.00,
                'compare_at_price' => 990000.00,
                'thumbnail_path' => 'content-marketing.jpg',
                'status' => 'published',
                'total_duration' => 18,
                'level' => 'beginner',
                'language' => 'Vietnamese',
                'enrolled_students' => 2450,
                'rating' => 4.5,
                'rating_count' => 610,
                'video_count' => 98,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => null,
                'category_id' => 7,
                'title' => 'Social Media Marketing toàn diện',
                'slug' => 'social-media-marketing',
                'short_description' => 'Xây dựng và phát triển thương hiệu trên mạng xã hội.',
                'description' => '<p>Chiến lược marketing trên Facebook, Instagram, TikTok, LinkedIn. Học content planning, engagement, influencer marketing, analytics, và community management.</p>',
                'price' => 579000.00,
                'compare_at_price' => 1090000.00,
                'thumbnail_path' => 'social-media.jpg',
                'status' => 'published',
                'total_duration' => 24,
                'level' => 'intermediate',
                'language' => 'Vietnamese',
                'enrolled_students' => 3100,
                'rating' => 4.6,
                'rating_count' => 780,
                'video_count' => 135,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Category 8: Kinh doanh
            [
                'instructor_id' => null,
                'category_id' => 8,
                'title' => 'Khởi nghiệp từ ý tưởng đến thực thi',
                'slug' => 'khoi-nghiep-startup',
                'short_description' => 'Xây dựng startup thành công từ zero với roadmap chi tiết.',
                'description' => '<p>Học cách validate ý tưởng, xây dựng MVP, tìm kiếm funding, pitching, scaling. Bao gồm Lean Startup, Business Model Canvas, và case study thực tế.</p>',
                'price' => 649000.00,
                'compare_at_price' => 1290000.00,
                'thumbnail_path' => 'startup.jpg',
                'status' => 'published',
                'total_duration' => 28,
                'level' => 'intermediate',
                'language' => 'Vietnamese',
                'enrolled_students' => 1950,
                'rating' => 4.7,
                'rating_count' => 480,
                'video_count' => 156,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => null,
                'category_id' => 8,
                'title' => 'Quản trị và Lãnh đạo hiệu quả',
                'slug' => 'quan-tri-lanh-dao',
                'short_description' => 'Phát triển kỹ năng quản lý đội nhóm và lãnh đạo tổ chức.',
                'description' => '<p>Nắm vững các kỹ năng quản lý: team building, delegation, motivation, conflict resolution, performance management, và strategic thinking.</p>',
                'price' => 599000.00,
                'compare_at_price' => 1190000.00,
                'thumbnail_path' => 'leadership.jpg',
                'status' => 'published',
                'total_duration' => 22,
                'level' => 'intermediate',
                'language' => 'Vietnamese',
                'enrolled_students' => 2300,
                'rating' => 4.6,
                'rating_count' => 560,
                'video_count' => 118,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => null,
                'category_id' => 8,
                'title' => 'Tài chính doanh nghiệp cơ bản',
                'slug' => 'tai-chinh-doanh-nghiep',
                'short_description' => 'Hiểu và quản lý tài chính cho doanh nghiệp vừa và nhỏ.',
                'description' => '<p>Học đọc báo cáo tài chính, cash flow management, budgeting, financial planning, ROI analysis, và các chỉ số tài chính quan trọng.</p>',
                'price' => 549000.00,
                'compare_at_price' => 1090000.00,
                'thumbnail_path' => 'finance.jpg',
                'status' => 'published',
                'total_duration' => 20,
                'level' => 'beginner',
                'language' => 'Vietnamese',
                'enrolled_students' => 1780,
                'rating' => 4.5,
                'rating_count' => 410,
                'video_count' => 105,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => null,
                'category_id' => 8,
                'title' => 'Chiến lược kinh doanh và Marketing',
                'slug' => 'chien-luoc-kinh-doanh',
                'short_description' => 'Xây dựng chiến lược phát triển doanh nghiệp bền vững.',
                'description' => '<p>Phát triển business strategy, competitive analysis, market positioning, growth hacking, customer acquisition, và sustainable business model.</p>',
                'price' => 629000.00,
                'compare_at_price' => 1190000.00,
                'thumbnail_path' => 'business-strategy.jpg',
                'status' => 'published',
                'total_duration' => 25,
                'level' => 'intermediate',
                'language' => 'Vietnamese',
                'enrolled_students' => 2150,
                'rating' => 4.7,
                'rating_count' => 520,
                'video_count' => 138,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Category 9: An ninh mạng
            [
                'instructor_id' => null,
                'category_id' => 9,
                'title' => 'Ethical Hacking cơ bản',
                'slug' => 'ethical-hacking-co-ban',
                'short_description' => 'Học penetration testing và bảo mật hệ thống từ đầu.',
                'description' => '<p>Nắm vững các kỹ thuật hacking đạo đức: reconnaissance, scanning, exploitation, post-exploitation. Thực hành trên lab với Kali Linux, Metasploit, Burp Suite.</p>',
                'price' => 749000.00,
                'compare_at_price' => 1490000.00,
                'thumbnail_path' => 'ethical-hacking.jpg',
                'status' => 'published',
                'total_duration' => 32,
                'level' => 'intermediate',
                'language' => 'Vietnamese',
                'enrolled_students' => 1620,
                'rating' => 4.8,
                'rating_count' => 420,
                'video_count' => 175,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => null,
                'category_id' => 9,
                'title' => 'Network Security & Firewall',
                'slug' => 'network-security-firewall',
                'short_description' => 'Bảo vệ hệ thống mạng với firewall và các công cụ security.',
                'description' => '<p>Học cách bảo mật network: firewall configuration, VPN, IDS/IPS, network monitoring, packet analysis với Wireshark, và incident response.</p>',
                'price' => 699000.00,
                'compare_at_price' => 1390000.00,
                'thumbnail_path' => 'network-security.jpg',
                'status' => 'published',
                'total_duration' => 28,
                'level' => 'intermediate',
                'language' => 'Vietnamese',
                'enrolled_students' => 1480,
                'rating' => 4.6,
                'rating_count' => 360,
                'video_count' => 148,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => null,
                'category_id' => 9,
                'title' => 'Web Application Security',
                'slug' => 'web-app-security',
                'short_description' => 'Bảo mật ứng dụng web - tìm và vá lỗ hổng OWASP Top 10.',
                'description' => '<p>Phát hiện và khắc phục các lỗ hổng web: SQL Injection, XSS, CSRF, authentication bypass. Học secure coding practices và web security testing.</p>',
                'price' => 649000.00,
                'compare_at_price' => 1290000.00,
                'thumbnail_path' => 'web-security.jpg',
                'status' => 'published',
                'total_duration' => 26,
                'level' => 'intermediate',
                'language' => 'Vietnamese',
                'enrolled_students' => 1850,
                'rating' => 4.7,
                'rating_count' => 460,
                'video_count' => 142,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => null,
                'category_id' => 9,
                'title' => 'Cryptography & Blockchain Security',
                'slug' => 'cryptography-blockchain',
                'short_description' => 'Mật mã học và bảo mật blockchain cho developer.',
                'description' => '<p>Hiểu về encryption, hashing, digital signatures, PKI, SSL/TLS. Tìm hiểu blockchain security, smart contract auditing, và crypto best practices.</p>',
                'price' => 699000.00,
                'compare_at_price' => 1390000.00,
                'thumbnail_path' => 'cryptography.jpg',
                'status' => 'published',
                'total_duration' => 24,
                'level' => 'advanced',
                'language' => 'Vietnamese',
                'enrolled_students' => 1320,
                'rating' => 4.5,
                'rating_count' => 290,
                'video_count' => 132,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert all demo courses
        DB::table('courses')->insert($demoCourses);

        $this->command->info('✅ Đã thêm 16 khóa học demo (4 khóa cho mỗi danh mục):');
        $this->command->info('   - Phát triển di động (4 khóa)');
        $this->command->info('   - Marketing số (4 khóa)');
        $this->command->info('   - Kinh doanh (4 khóa)');
        $this->command->info('   - An ninh mạng (4 khóa)');
    }
}
